### ISSUE TITLE
[doc] system architecture map

### ISSUE THREAD

**Issue by duidae** [kids-reporter/kids-reporter-monorepo#285]

**Comment by nickhsine** [comment]
~先畫了一個版本的 system design，請兩位 @duidae @howar31 幫忙看一下有沒有缺漏？也順帶討論一下，整個系統架構圖要放在哪個 README.md 底下？~

**Comment by duidae** [comment]
這個放在公開會不有點風險? 🤔 (之前開這issue是怕忘記所以找個地方紀錄一下)

**Comment by nickhsine** [comment]
好像沒有什麼機密資訊？
但是有疑慮的話，我們移回 slack 討論好了。

**Comment by duidae** [comment]
closed due to duplicate issue in asana
