### ISSUE TITLE
Remove frontend warning in console: Warning: Prop `data-editor` did not match. Server: "7v719" Client: "1p4qo"

### ISSUE THREAD

**Issue by duidae** [kids-reporter/kids-reporter-monorepo#92]
https://adminhk.com/draft-js-next-js-%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8%E6%99%82%E9%81%87%E4%B8%8A%E7%9A%84%E5%9D%91/

**Comment by nickhsine** [comment]
This warning message is caused by styled-components.
After we adjust `next.config.js`, see https://github.com/kids-reporter/kids-reporter-monorepo/blob/dev/packages/frontend/next.config.js#L5-L7, this issue has been fixed.
